# Generated by Django 5.2.8 on 2025-11-14 21:08

import machines.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-friendly name of the machine (e.g. 'web-01', 'db-prod-1').",
                        max_length=150,
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True,
                        help_text="Optional hostname reported by the agent.",
                        max_length=255,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Last known IP address of the machine.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description, environment, or notes.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive machines will not be allowed to send logs.",
                    ),
                ),
                (
                    "api_token",
                    models.CharField(
                        default=machines.models.generate_machine_token,
                        help_text="Secret token issued to the machine for API access.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time the agent successfully contacted the server.",
                        null=True,
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the machine was initially registered.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Machine",
                "verbose_name_plural": "Machines",
                "db_table": "machines_machine",
                "ordering": ["-created_at"],
            },
        ),
    ]
