# Create your models here.
from __future__ import annotations

from django.db import models

from core.models import TimeStampedModel, SeverityLevel
from machines.models import Machine
from rules.models import Rule


class AlertStatus(models.TextChoices):
    OPEN = "open", "Open"
    ACKNOWLEDGED = "ack", "Acknowledged"
    RESOLVED = "resolved", "Resolved"
    SUPPRESSED = "suppressed", "Suppressed"


class Alert(TimeStampedModel):
    """
    Security alert generated by the rule engine.

    Alerts aggregate one or more log events that match a given rule and share
    a deduplication key (e.g. same machine + IP + rule within a time window).
    """

    machine = models.ForeignKey(
        Machine,
        on_delete=models.CASCADE,
        related_name="alerts",
        help_text="Machine on which this alert was detected.",
    )
    rule = models.ForeignKey(
        Rule,
        on_delete=models.PROTECT,
        related_name="alerts",
        help_text="Rule that generated this alert.",
    )

    title = models.CharField(
        max_length=200,
        help_text="Short human-readable summary of the alert.",
    )
    message = models.TextField(
        help_text="Detailed description of the alert and context.",
    )

    severity = models.CharField(
        max_length=16,
        choices=SeverityLevel.choices,
        default=SeverityLevel.MEDIUM,
        db_index=True,
        help_text="Severity level of this specific alert instance.",
    )

    status = models.CharField(
        max_length=16,
        choices=AlertStatus.choices,
        default=AlertStatus.OPEN,
        db_index=True,
        help_text="Current lifecycle status of the alert.",
    )

    source_ip = models.GenericIPAddressField(
        null=True,
        blank=True,
        db_index=True,
        help_text="Source IP associated with this alert (if applicable).",
    )

    first_seen = models.DateTimeField(
        help_text="When the condition was first observed.",
    )
    last_seen = models.DateTimeField(
        help_text="Most recent time the condition was observed.",
    )

    occurrence_count = models.PositiveIntegerField(
        default=1,
        help_text="Number of events aggregated into this alert.",
    )

    deduplication_key = models.CharField(
        max_length=255,
        db_index=True,
        help_text=(
            "Key used by the alert engine to group duplicate alerts "
            "(e.g. machine+rule+source_ip)."
        ),
    )

    metadata = models.JSONField(
        default=dict,
        blank=True,
        help_text="Additional context (ports, usernames, sample logs, etc.).",
    )

    class Meta:
        db_table = "alerts_alert"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["machine", "severity", "status"]),
            models.Index(fields=["deduplication_key"]),
        ]
        verbose_name = "Alert"
        verbose_name_plural = "Alerts"

    def __str__(self) -> str:
        return f"[{self.severity}] {self.title} ({self.machine})"
