# Generated by Django 5.2.8 on 2025-11-14 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("machines", "0001_initial"),
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Short human-readable summary of the alert.",
                        max_length=200,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Detailed description of the alert and context."
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        help_text="Severity level of this specific alert instance.",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("ack", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("suppressed", "Suppressed"),
                        ],
                        db_index=True,
                        default="open",
                        help_text="Current lifecycle status of the alert.",
                        max_length=16,
                    ),
                ),
                (
                    "source_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        db_index=True,
                        help_text="Source IP associated with this alert (if applicable).",
                        null=True,
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        help_text="When the condition was first observed."
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        help_text="Most recent time the condition was observed."
                    ),
                ),
                (
                    "occurrence_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of events aggregated into this alert.",
                    ),
                ),
                (
                    "deduplication_key",
                    models.CharField(
                        db_index=True,
                        help_text="Key used by the alert engine to group duplicate alerts (e.g. machine+rule+source_ip).",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (ports, usernames, sample logs, etc.).",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        help_text="Machine on which this alert was detected.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="machines.machine",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        help_text="Rule that generated this alert.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alerts",
                        to="rules.rule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
                "db_table": "alerts_alert",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["machine", "severity", "status"],
                        name="alerts_aler_machine_fb8eeb_idx",
                    ),
                    models.Index(
                        fields=["deduplication_key"],
                        name="alerts_aler_dedupli_5b3e5f_idx",
                    ),
                ],
            },
        ),
    ]
