# Generated by Django 5.2.8 on 2025-11-15 11:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0001_initial"),
        ("machines", "0001_initial"),
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={"ordering": ["-last_seen", "-severity", "-occurrences"]},
        ),
        migrations.RemoveIndex(
            model_name="alert",
            name="alerts_aler_machine_fb8eeb_idx",
        ),
        migrations.RemoveIndex(
            model_name="alert",
            name="alerts_aler_dedupli_5b3e5f_idx",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="deduplication_key",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="message",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="occurrence_count",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="source_ip",
        ),
        migrations.AddField(
            model_name="alert",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="is_escalated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alert",
            name="occurrences",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="alert",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="alert",
            name="first_seen",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="alert",
            name="last_seen",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="alert",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="machines.machine",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="alert",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="rules.rule",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="low",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("ack", "Acknowledged"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="alert",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name="alert",
            table=None,
        ),
    ]
