# Generated by Django 5.2.8 on 2025-11-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0002_alter_alert_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={
                "ordering": [
                    "-last_seen",
                    "-severity",
                    "-occurrence_count",
                    "-occurrences",
                ]
            },
        ),
        migrations.AddField(
            model_name="alert",
            name="occurrence_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Mirror of occurrences, kept for backward compatibility and tests.",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="source_ip",
            field=models.CharField(
                blank=True,
                help_text="Source IP address that triggered this alert (if applicable).",
                max_length=64,
                null=True,
            ),
        ),
    ]
