# Generated by Django 5.2.8 on 2025-11-14 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("machines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Timestamp when the event occurred on the source machine.",
                    ),
                ),
                (
                    "ingested_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this log entry was ingested by SIEM-Lite.",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Normalized event type (e.g. 'ssh_failed_login', 'sudo_command').",
                        max_length=64,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="info",
                        help_text="Optional severity level assigned during ingestion.",
                        max_length=16,
                    ),
                ),
                (
                    "raw_message",
                    models.TextField(help_text="Original raw log line or message."),
                ),
                (
                    "source_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        db_index=True,
                        help_text="Source IP address if available (for network/SSH events).",
                        null=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Username if applicable to this log entry.",
                        max_length=150,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional normalized fields (port, process, path, etc.).",
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optional correlation key to group related logs together.",
                        max_length=64,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        help_text="Machine that produced this log entry.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="machines.machine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log entry",
                "verbose_name_plural": "Log entries",
                "db_table": "logs_logentry",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="logs_logent_event_t_ac20eb_idx",
                    ),
                    models.Index(
                        fields=["machine", "timestamp"],
                        name="logs_logent_machine_b99b6f_idx",
                    ),
                ],
            },
        ),
    ]
