# Generated by Django 5.2.8 on 2025-11-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name of the rule.",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable slug identifier for programmatic reference.",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this rule detects.",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disabled rules are ignored by the rule engine.",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Normalized event_type that this rule applies to (e.g. 'ssh_failed_login').",
                        max_length=64,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Default severity level for alerts produced by this rule.",
                        max_length=16,
                    ),
                ),
                (
                    "threshold",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Minimum number of matching events within the window to trigger an alert.",
                    ),
                ),
                (
                    "window_minutes",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Time window in minutes over which events are counted.",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional engine-specific parameters or conditions.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule",
                "verbose_name_plural": "Rules",
                "db_table": "rules_rule",
                "ordering": ["name"],
            },
        ),
    ]
